#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "jellybeans"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    # Disable relative line number
    relativenumber = false
    # terminal_cursor_shape = 0
    # vimfiler options
    enable_vimfiler_gitstatus = true
    # bootstrap functions
    bootstrap_after = "cursor#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "default"

[[layers]]
name = "ctrlspace"

[[layers]]
name = "VersionControl"

[[layers]]
name = "fzf"

[[layers]]
name = "colorscheme"

[[layes]]
name = "core#statusline"

[[layers]]
name = "incsearch"

[[layers]]
name = "tmux"

[[layers]]
name = "git"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 20

[[layers]]
name = "lang#clojure"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#ruby"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#scala"

