[[snippets]]
  description = "ssh into service pod"
  command = "nu-<nu=br> k8s ssh global <service=veiga> --env <env=staging>"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Xargs + seq date example"
  command = "for d in $(seq 1 <num-days=30>); do echo <input-to-concat>$(date -d \"<yyyyMMdd> $d days\" +%Y%m%d); done | xargs -P <batch> -n 1 <command>"
  output = ""

[[snippets]]
  description = "Xargs + for example"
  command = "for i in {01..<max=20>}; do echo <input-to-concat>$i; done | xargs -P <batch> -n 1 <command>"
  output = ""

[[snippets]]
  description = "Weather"
  command = "curl wttr.in/Berlin"
  output = ""

[[snippets]]
  description = "Watching pods"
  command = "watch -n 10 \"nu-<nu=br> k8s ctl --env <env=prod> --stack-id <stack=blue> <prototype=s0> -- get pods -l nubank.com.br/name=<service=correnteza> --field-selector=status.phase=Running\""
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Uncommit dataset and predecessors"
  command = "nu datainfra hausmeister dataset-uncommit <transaction-id> <dataset-name> --include-predecessors"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Service health check on all shards"
  command = "nu-<nu=br> on-shards run -- ser curl GET % <service=correnteza> /ops/health"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Service configuration"
  command = "nu-<nu=br> ser curl GET --env <env=prod> <prototype=global> <service=barragem> /ops/config/dump | jq . | less"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Scale k8s service"
  command = "nu-<nu=br> k8s scale --env <env=prod> <prototype=global> <service=barragem> <current> --min <min> --max <max>"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Repl into service pod"
  command = "nu-<nu=data> k8s repl global <service=metapod> --env <env=staging>"
  output = ""

[[snippets]]
  description = "My public ip"
  command = "curl eth0.me"
  output = ""

[[snippets]]
  description = "Improved Weather"
  command = "curl -s \"https://wttr.in/Berlin?m2F&format=v2\""
  output = ""

[[snippets]]
  description = "Getting path for given resource on dataset-series"
  command = "nu-<country=br> ser curl GET --env <env=staging> global ouroboros /api/admin/debug/resource/<resource-id>"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Edit pod configuration"
  command = "nu-<nu=br> k8s ctl --env \"<env=prod>\" \"<prototype=s0>\" -- edit deploy \"<env=prod>-<prototype=s0>-<stack=blue>-<service=correnteza>-deployment\""
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Cycle a service on a given prototype"
  command = "nu-<nu=br> k8s cycle --env <env=prod> <prototype=s0> <service>"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Counting descriptors by process"
  command = "lsof -n | ruby -e 'h = Hash.new(0); STDIN.each_line{|l| h[l.split[1]] += 1}; p h.to_a.sort{|a,b| a[1] <=> b[1]}'"
  output = ""

[[snippets]]
  description = "Commit dataset empty"
  command = "nu-<nu=data> datainfra sabesp -- metapod --token --env prod dataset commit <transactionId> <datasetId> PARQUET s3://nu-spark-us-east-1/non-datomic/static-datasets/empty-materialized/empty.gz.parquet"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Checks state of dataset commits and paths"
  command = "nu-<nu=br> etl info <dataset=dataset/savings-balances> --n=<hit_size=10>"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Checking k8s prototype state"
  command = "nu-<nu=br> k8s ctl <prototype=s0> --env <env=prod> --stack-id blue -- get pods -l nubank.com.br/name=<service=correnteza>"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Check logs of previous pods for a service"
  command = "nu-<nu=br> k8s logs --env <env=prod> --stack-id blue <prototype=s0> <service=correnteza> --pod <pod> -- --previous | less"
  tag = ["nu"]
  output = ""

[[snippets]]
  description = "Force attempt checker on all correnteza shards"
  command = "nu on-shards run -- ser curl POST % correnteza /ops/attempt-checker/force"
  tag = ["nu"]
  output = ""
