[[snippets]]
  description = "[nu] Watching pods"
  command = "watch -n 10 \"nu-<nu=br> k8s ctl --country <country=br> --env <env=prod> --stack-id <stack=blue> <prototype=s0> -- get pods -l nubank.com.br/name=<service=correnteza> --field-selector=status.phase=Running\""
  output = ""

[[snippets]]
  description = "[nu] Service health check on all shards"
  command = "nu-<nu=br> on-shards run -- ser curl GET % <service=correnteza> /ops/health"
  output = ""

[[snippets]]
  description = "[nu] Checking k8s prototype state"
  command = "nu-<nu=br> k8s ctl <prototype=s0> --env <env=prod> --stack-id blue -- get pods -l nubank.com.br/name=<service=correnteza>"
  output = ""

[[snippets]]
  description = "[nu] Check logs of previous pods for a service"
  command = "nu-<nu=br> k8s logs --env <env=prod> --stack-id blue <prototype=s0> <service=correnteza> --pod <pod> -- --previous | less"
  output = ""

[[snippets]]
  description = "Xargs + seq date example"
  command = "for d in $(seq 1 <num-days=30>); do echo <input-to-concat>$(date -d \"<yyyyMMdd> $d days\" +%Y%m%d); done | xargs -P <batch> -n 1 <command>"
  output = ""

[[snippets]]
  description = "Xargs + for example"
  command = "for i in {01..<max=20>}; do echo <input-to-concat>$i; done | xargs -P <batch> -n 1 <command>"
  output = ""

[[snippets]]
  description = "Weather"
  command = "curl wttr.in/Berlin"
  output = ""

[[snippets]]
  description = "My public ip"
  command = "curl eth0.me"
  output = ""

[[snippets]]
  description = "Improved Weather"
  command = "curl -s \"https://wttr.in/Berlin?m2F&format=v2\""
  output = ""

[[snippets]]
  description = "Counting descriptors by process"
  command = "lsof -n | ruby -e 'h = Hash.new(0); STDIN.each_line{|l| h[l.split[1]] += 1}; p h.to_a.sort{|a,b| a[1] <=> b[1]}'"
  output = ""

[[snippets]]
  description = "[nu] Cycle a service on a given prototype"
  command = "nu-<nu=br> k8s cycle --country <country=br> --env <env=prod> <prototype=s0> <service>"
  output = ""
